name: Bug Report
description: File a report for a non-blocking bug, i.e., issues that can be worked around.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Affected tools
      description: Which tools are affected by this bug?
      options:
        - label: cbuild
          required: false
        - label: cbuild2cmake
          required: false
        - label: cpackget
          required: false
        - label: csolution
          required: false
        - label: packchk
          required: false
        - label: svdconv
          required: false
  - type: checkboxes
    attributes:
      label: Affected operating systems
      description: On which host os platforms does the bug occur?
      options:
        - label: Windows amd64
          required: false
        - label: Windows arm64
          required: false
        - label: Linux amd64
          required: false
        - label: Linux arm64
          required: false
        - label: MacOS amd64
          required: false
        - label: MacOS arm64
          required: false
  - type: textarea
    attributes:
      label: Environment
      description: Give more details about the affected operating system(s), e.g. distribution and version.
      placeholder: |
        - Ubuntu 22.04
        - Windows 10 Version 22H2 (Build ...)
    validations:
      required: false
