name: "Feature Request"
description: "Submit a new feature request"
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: input
    id: title
    attributes:
      label: "Short Summary"
      description: "Provide a brief title for the request."

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a detailed description of the request, including the problem it solves and any relevant context."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define the conditions that must be met for this request to be considered complete."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Select the priority level of this request."
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: related_issues
    attributes:
      label: "Related Issues (Optional)"
      description: "Link any related GitHub issues."
      placeholder: "e.g., #123, #456"

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes (Optional)"
      description: "Provide any extra information or concerns regarding this request."
