*** Variables ***
${RESOURCES}              ${CURDIR}          # Path to the resource directory
${Build}                  build              # Directory name where example build files are copied
${Data}                   data               # Directory name of test data source
${Pass}                   ${0}               # Exit status pass
${Fail}                   ${1}               # Exit status fail
${Out_Dir}                out_dir            # 
${Default_Out_Dir}        out                # Default name of the output directory
${Remote_Example_Dir}     remote_examples    # Directory name for remote examples
${Local_Pack_Root_Dir}    pack_root_dir      # Directory name for local pack root directory