name: global
on:
  pull_request:
    paths:
      - '!docs/**'
      - '!README.md'
  release:
    types: [ published ]
jobs:
  copyright:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout devtools
        uses: actions/checkout@v4

      - name: Check copyright notice
        run: |
          pip install \
            pre-commit \
            python-magic==0.4.18 \
            comment-parser>=1.2.3
          pre-commit run --all-files
