name: Robot Tests

on:
  pull_request:
    paths:
      - '.github/workflows/robot-tests.yml'
      - 'test/**'
      - '!test/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pip dependencies
        run: |
            pip install --upgrade pip
            pip install -r test/requirements.txt

      # - name: Cache vcpkg
      #   uses: actions/cache@v4
      #   with:
      #     key: vcpkg-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
      #     restore-keys: |
      #         vcpkg-${{ runner.os }}-${{ runner.arch }}-
      #     path: /home/runner/.vcpkg
    
      # - name: Prepare vcpkg env
      #   working-directory: ./test
      #   run: |  
      #     . <(curl https://aka.ms/vcpkg-init.sh -L)
      #     vcpkg x-update-registry --all
      #     vcpkg activate

      - name: Setup vcpkg environment
        uses: soumeh01/actions/vcpkg@testwindows
        with:
          config: "./test/vcpkg-configuration.json"
          vcpkg-root: "${{ github.workspace }}/.vcpkg"
          cache: "-"

      - name: Activate Arm tool license
        working-directory: ./test
        run: |
          armlm activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0

      - name: Run Test
        continue-on-error: true
        working-directory: ./test
        run: |
          python -m robot --outputdir ../reports-${{ matrix.os }} -x junit-report.xml src

      - name: Archieve test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.os }}
          path: reports-${{ matrix.os }}

  report:
    runs-on: ubuntu-latest
    if: always()
    needs: test
    permissions: write-all
    steps:
    - uses: actions/checkout@v4

    - name: Download reports windows
      uses: actions/download-artifact@v4
      with:
        name: reports-windows-latest
        path: reports-windows-latest

    - name: Download reports linux
      uses: actions/download-artifact@v4
      with:
        name: reports-ubuntu-latest
        path: reports-ubuntu-latest

    - name: Download reports darwin
      uses: actions/download-artifact@v4
      with:
        name: reports-macos-latest
        path: reports-macos-latest

    - name: Send windows report to commit
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        report_path: reports-windows-latest
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Send linux report to commit
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        report_path: reports-ubuntu-latest
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Send macos report to commit
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        report_path: reports-macos-latest
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
